// <auto-generated />
using System;
using BomberosAPI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BomberosAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BomberosAPI.Domain.Entities.AccessAudit", b =>
                {
                    b.Property<Guid>("AccessAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("access_audit_id");

                    b.Property<Guid?>("AuthSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auth_session_id");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("event");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<bool>("Success")
                        .HasColumnType("bit")
                        .HasColumnName("success");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AccessAuditId");

                    b.ToTable("AccessAudit", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.AuthSession", b =>
                {
                    b.Property<Guid>("AuthSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auth_session_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("device");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Ip")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("ip");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("AuthSessionId");

                    b.ToTable("AuthSession", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.BioimpedanceMeasurement", b =>
                {
                    b.Property<Guid>("BioimpedanceMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("bioimpedance_measurement_id");

                    b.Property<decimal?>("BasalMetabolicRate")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("basal_metabolic_rate");

                    b.Property<decimal?>("BodyWaterPct")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("body_water_pct");

                    b.Property<decimal?>("FatPercentage")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("fat_percentage");

                    b.Property<decimal?>("MuscleMassKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("muscle_mass_kg");

                    b.Property<Guid>("RegisteredByHealthPersonnelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registered_by_health_personnel_id");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("taken_at");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("BioimpedanceMeasurementId");

                    b.ToTable("BioimpedanceMeasurement", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.ChangeAudit", b =>
                {
                    b.Property<Guid>("ChangeAuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("change_audit_id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("entity");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entity_id");

                    b.Property<string>("NewValuesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values_json");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operation");

                    b.Property<string>("PreviousValuesJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("previous_values_json");

                    b.HasKey("ChangeAuditId");

                    b.ToTable("ChangeAudit", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.ConsentDocument", b =>
                {
                    b.Property<Guid>("ConsentDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("consent_document_id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("consent_type");

                    b.Property<string>("TextContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_content");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("valid_until");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("version");

                    b.HasKey("ConsentDocumentId");

                    b.ToTable("ConsentDocument", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.CriticalAlert", b =>
                {
                    b.Property<Guid>("CriticalAlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("critical_alert_id");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alert_type");

                    b.Property<DateTime?>("AttendedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("attended_at");

                    b.Property<Guid?>("AttendedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("attended_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EnvironmentalDataId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("environmental_data_id");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SymptomReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_report_id");

                    b.Property<Guid?>("VitalSignsMeasurementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vital_signs_measurement_id");

                    b.HasKey("CriticalAlertId");

                    b.ToTable("CriticalAlert", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.DSARRequest", b =>
                {
                    b.Property<Guid>("DSARRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("dsar_request_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("LegalDeadlineAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("legal_deadline_at");

                    b.Property<Guid?>("ManagedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("managed_by_user_id");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("requested_at");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<string>("Response")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response");

                    b.Property<string>("RightType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("right_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("DSARRequestId");

                    b.ToTable("DSARRequest", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.EnvironmentalData", b =>
                {
                    b.Property<Guid>("EnvironmentalDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("environmental_data_id");

                    b.Property<decimal?>("CoPpm")
                        .HasPrecision(7, 2)
                        .HasColumnType("decimal(7,2)")
                        .HasColumnName("co_ppm");

                    b.Property<decimal?>("HeatStressIndex")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("heat_stress_index");

                    b.Property<decimal?>("HumidityPct")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("humidity_pct");

                    b.Property<DateTime>("MeasuredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("measured_at");

                    b.Property<Guid>("RegisteredByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registered_by_user_id");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("temperature_c");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.HasKey("EnvironmentalDataId");

                    b.ToTable("EnvironmentalData", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.HealthPersonnel", b =>
                {
                    b.Property<Guid>("HealthPersonnelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("health_personnel_id");

                    b.Property<bool>("CanApproveDischarges")
                        .HasColumnType("bit")
                        .HasColumnName("can_approve_discharges");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("license_number");

                    b.Property<string>("Profession")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("profession");

                    b.Property<string>("Specialty")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("specialty");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("HealthPersonnelId");

                    b.ToTable("HealthPersonnel", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.Invitation", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invitation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitationTokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("invitation_token_hash");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("responded_at");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_user_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TargetEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("target_email");

                    b.Property<Guid?>("TargetRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_role_id");

                    b.Property<Guid?>("TargetUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("target_user_id");

                    b.Property<Guid?>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.HasKey("InvitationId");

                    b.ToTable("Invitation", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.MedicalHistory", b =>
                {
                    b.Property<Guid>("MedicalHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("medical_history_id");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allergies");

                    b.Property<Guid>("CreatedByHealthPersonnelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_health_personnel_id");

                    b.Property<string>("CurrentMedication")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_medication");

                    b.Property<string>("GeneralObservations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("general_observations");

                    b.Property<string>("PreexistingConditions")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("preexisting_conditions");

                    b.Property<Guid>("TraineeFirefighterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainee_firefighter_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("MedicalHistoryId");

                    b.ToTable("MedicalHistory", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.OfflineSyncQueue", b =>
                {
                    b.Property<Guid>("OfflineSyncQueueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("offline_sync_queue_id");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("int")
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payload_json");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("record_id");

                    b.Property<string>("SourceTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_table");

                    b.Property<bool>("Synced")
                        .HasColumnType("bit")
                        .HasColumnName("synced");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("synced_at");

                    b.HasKey("OfflineSyncQueueId");

                    b.ToTable("OfflineSyncQueue", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("PasswordResetTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("password_reset_token_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("PasswordResetTokenId");

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.SessionParticipant", b =>
                {
                    b.Property<Guid>("SessionParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<bool>("AttendanceConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("attendance_confirmed");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("check_in_at");

                    b.Property<Guid?>("InvitationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invitation_id");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("observations");

                    b.Property<string>("ParticipationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("participation_status");

                    b.Property<Guid>("TraineeFirefighterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainee_firefighter_id");

                    b.Property<Guid>("TrainingSessionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.HasKey("SessionParticipantId");

                    b.ToTable("SessionParticipant", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.SessionResult", b =>
                {
                    b.Property<Guid>("SessionResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_result_id");

                    b.Property<bool>("FitToContinue")
                        .HasColumnType("bit")
                        .HasColumnName("fit_to_continue");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at");

                    b.Property<decimal?>("PerformanceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("performance_score");

                    b.Property<string>("RiskClassification")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("risk_classification");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<Guid>("ValidatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("validated_by_user_id");

                    b.HasKey("SessionResultId");

                    b.ToTable("SessionResult", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.SymptomReport", b =>
                {
                    b.Property<Guid>("SymptomReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("symptom_report_id");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reported_by_user_id");

                    b.Property<bool>("RequiresAlert")
                        .HasColumnType("bit")
                        .HasColumnName("requires_alert");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Symptoms")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("symptoms");

                    b.HasKey("SymptomReportId");

                    b.ToTable("SymptomReport", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.TraineeFirefighter", b =>
                {
                    b.Property<Guid>("TraineeFirefighterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("trainee_firefighter_id");

                    b.Property<string>("ApplicantCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("applicant_code");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("BloodType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("blood_type");

                    b.Property<string>("EmergencyContactName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("sex");

                    b.Property<string>("TrainingStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("training_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("TraineeFirefighterId");

                    b.ToTable("TraineeFirefighter", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.TrainingInstitution", b =>
                {
                    b.Property<Guid>("InstitutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("institution_id");

                    b.Property<string>("Acronym")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("acronym");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("country");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("InstitutionId");

                    b.ToTable("TrainingInstitution", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.TrainingLocation", b =>
                {
                    b.Property<Guid>("TrainingLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_location_id");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("address");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("institution_id");

                    b.Property<string>("LocationType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("location_type");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("int")
                        .HasColumnName("max_capacity");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("TrainingLocationId");

                    b.ToTable("TrainingLocation", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.TrainingSession", b =>
                {
                    b.Property<Guid>("TrainingSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_session_id");

                    b.Property<DateTime?>("ActualEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_end");

                    b.Property<DateTime?>("ActualStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_start");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("institution_id");

                    b.Property<int?>("PlannedCapacity")
                        .HasColumnType("int")
                        .HasColumnName("planned_capacity");

                    b.Property<DateTime>("ScheduledEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_end");

                    b.Property<DateTime>("ScheduledStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_start");

                    b.Property<string>("SessionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<Guid>("TrainingLocationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("training_location_id");

                    b.HasKey("TrainingSessionId");

                    b.ToTable("TrainingSession", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("account_status");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("first_name");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("institution_id");

                    b.Property<DateTime?>("LastAccessAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_access_at");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("phone");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.UserConsent", b =>
                {
                    b.Property<Guid>("UserConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_consent_id");

                    b.Property<Guid>("ConsentDocumentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("consent_document_id");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("granted_at");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("institution_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("UserConsentId");

                    b.ToTable("UserConsent", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.UserCredential", b =>
                {
                    b.Property<Guid>("UserCredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_credential_id");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_attempts");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hash_algorithm");

                    b.Property<DateTime?>("LastPasswordChangeAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_password_change_at");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("datetime2")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("UserCredentialId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserCredential", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_role_id");

                    b.Property<Guid?>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("BomberosAPI.Domain.Entities.VitalSignsMeasurement", b =>
                {
                    b.Property<Guid>("VitalSignsMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("vital_signs_measurement_id");

                    b.Property<decimal?>("DiastolicPressure")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("diastolic_pressure");

                    b.Property<decimal?>("HeartRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("heart_rate");

                    b.Property<Guid>("RegisteredByHealthPersonnelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("registered_by_health_personnel_id");

                    b.Property<Guid>("SessionParticipantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("session_participant_id");

                    b.Property<decimal?>("Spo2")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("spo2");

                    b.Property<decimal?>("SystolicPressure")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("systolic_pressure");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("taken_at");

                    b.Property<decimal?>("TemperatureC")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)")
                        .HasColumnName("temperature_c");

                    b.HasKey("VitalSignsMeasurementId");

                    b.ToTable("VitalSignsMeasurement", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
